name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    - name: Restore dependencies
      run: dotnet restore Project28.sln
    - name: Build
      run: dotnet build --no-restore Project28.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Project28.sln
