name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    - name: Restore dependencies
      run: dotnet restore Project28.sln
    - name: Build
      run: dotnet build --no-restore Project28.sln
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" --no-build --verbosity normal Project28.sln
    - name: Upload code coverage report
      uses: codecov/codecov-action@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image for Raspberry Pi
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: mu88/thisisyourlife:latest
        file: src/WebApp/Dockerfile
    - name: Build single-file EXE
      run: dotnet publish src/WebApp/WebApp.csproj -r win-x64 -p:PublishSingleFile=true --self-contained true